import React, { useEffect, useState } from "react";
import { Bar } from "react-chartjs-2";
import {
  Chart as ChartJS, CategoryScale, LinearScale,
  BarElement, Title, Tooltip, Legend,
} from "chart.js";

ChartJS.register(CategoryScale, LinearScale, BarElement, Title, Tooltip, Legend);

const RISK_LABELS = { 0: "Low Risk", 1: "Moderate Risk", 2: "High Risk" };
const RISK_COLORS = { 0: "#4caf50", 1: "#ff9800", 2: "#f44336" };

const GrowthReport = () => {
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [isMobile, setIsMobile] = useState(false);

  useEffect(() => {
    const checkIfMobile = () => setIsMobile(window.innerWidth <= 768);
    checkIfMobile();
    window.addEventListener("resize", checkIfMobile);
    return () => window.removeEventListener("resize", checkIfMobile);
  }, []);

  useEffect(() => {
    const fetchReport = async () => {
      try {
        const answers = JSON.parse(localStorage.getItem("mentalHealthAnswers"));
        if (!answers) {
          setError("No answers found. Please complete the assessment first.");
          setLoading(false);
          return;
        }

        const res = await fetch(
          `${import.meta.env.VITE_API_URL}/api/predict`,
          {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify(answers),
          }
        );

        if (!res.ok) throw new Error("Failed to get prediction from server.");
        const data = await res.json();
        setReport(data);
      } catch (err) {
        setError(err.message || "Something went wrong.");
      } finally {
        setLoading(false);
      }
    };

    fetchReport();
  }, []);

  if (loading)
    return (
      <div className="growth-report">
        <h2>Analyzing your responses...</h2>
        <p>Please wait while our AI generates your personalized mental health report.</p>
      </div>
    );

  if (error)
    return (
      <div className="growth-report">
        <h2>Error</h2>
        <p>{error}</p>
      </div>
    );

  const riskColor = RISK_COLORS[report.prediction] || "#607d8b";

  const chartData = {
    labels: report.scores.map((s) => s.label),
    datasets: [
      {
        label: "Your Score",
        data: report.scores.map((s) => s.value),
        backgroundColor: "rgba(75, 192, 192, 0.6)",
        borderColor: "rgba(75, 192, 192, 1)",
        borderWidth: 1,
      },
    ],
  };

  const chartOptions = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      legend: { position: "top" },
      title: { display: true, text: "Your Mental Health Profile" },
    },
    scales: {
      y: { beginAtZero: true, max: 5, ticks: { stepSize: 1 } },
      x: {
        ticks: {
          maxRotation: isMobile ? 45 : 0,
          minRotation: isMobile ? 45 : 0,
        },
      },
    },
  };

  return (
    <div className="growth-report">
      <h2>Your Mental Health Report</h2>

      {/* Risk Badge */}
      <div
        className="risk-badge"
        style={{
          background: riskColor, color: "#fff", padding: "12px 24px",
          borderRadius: "8px", display: "inline-block", marginBottom: "24px",
          fontSize: "1.2rem", fontWeight: "bold"
        }}
      >
        Mental Health Risk Level: {RISK_LABELS[report.prediction]}
      </div>

      {/* Bar Chart */}
      <div className="chart-container" style={{ height: isMobile ? "260px" : "340px" }}>
        <Bar data={chartData} options={chartOptions} />
      </div>

      {/* AI Generated Professional Report */}
      <div className="insights-container" style={{ marginTop: "32px" }}>
        <h3>Professional Assessment</h3>
        <div className="insight-card" style={{ whiteSpace: "pre-line" }}>
          {report.professional_report}
        </div>
      </div>

      {/* Recommendations */}
      <div className="advice-container" style={{ marginTop: "24px" }}>
        <h3>Personalized Recommendations</h3>
        <div className="advice-card">
          <ul>
            {report.recommendations.map((rec, i) => (
              <li key={i}>{rec}</li>
            ))}
          </ul>
        </div>
      </div>

      <p style={{ marginTop: "24px", fontSize: "0.85rem", color: "#888" }}>
        * This report is generated by AI for informational purposes only and does not replace professional medical advice.
      </p>
    </div>
  );
};

export default GrowthReport;